package anesthesia.record;

public class BeanTarget {
	String ANESTHESIA_ID,OPERATION_ID,CASE_OBJECT_ID,ANESTHESIA_METHODS,ANAESTHETIST_ID,ANESTHESIA_BEGIN,ANESTHESIA_END,ASA_LEVEL_CD,SPILE_SORT,ANESTHESIA_POSTURE,BREATHE_TYPE_CD,ANESTHESIA_DESCRIBE,ANESTHESIA_COMPL_CD,PUNCTURE_SORT_CD,PUNCTURE_PROC,ANESTHESIA_EFFECT,PREANAESTHETIC_MEDICINE,WEIGHT,TEMPERATURE,PULSE,BREATHE_RATE,SYSTOLIC_PRESSURE,DIASTOLIC_PRESSURE,ENTER_DATE_TIME,IN_DATE_TIME,OUT_DATE_TIME,SCHEDULED_DATE_TIME;

	public String getSCHEDULED_DATE_TIME() {
		return SCHEDULED_DATE_TIME;
	}

	public void setSCHEDULED_DATE_TIME(String sCHEDULED_DATE_TIME) {
		SCHEDULED_DATE_TIME = sCHEDULED_DATE_TIME;
	}

	public String getANESTHESIA_ID() {
		return ANESTHESIA_ID;
	}

	public void setANESTHESIA_ID(String aNESTHESIA_ID) {
		ANESTHESIA_ID = aNESTHESIA_ID;
	}

	public String getOPERATION_ID() {
		return OPERATION_ID;
	}

	public void setOPERATION_ID(String oPERATION_ID) {
		OPERATION_ID = oPERATION_ID;
	}

	public String getCASE_OBJECT_ID() {
		return CASE_OBJECT_ID;
	}

	public void setCASE_OBJECT_ID(String cASE_OBJECT_ID) {
		CASE_OBJECT_ID = cASE_OBJECT_ID;
	}

	public String getANESTHESIA_METHODS() {
		return ANESTHESIA_METHODS;
	}

	public void setANESTHESIA_METHODS(String aNESTHESIA_METHODS) {
		ANESTHESIA_METHODS = aNESTHESIA_METHODS;
	}

	public String getANAESTHETIST_ID() {
		return ANAESTHETIST_ID;
	}

	public void setANAESTHETIST_ID(String aNAESTHETIST_ID) {
		ANAESTHETIST_ID = aNAESTHETIST_ID;
	}

	public String getANESTHESIA_BEGIN() {
		return ANESTHESIA_BEGIN;
	}

	public void setANESTHESIA_BEGIN(String aNESTHESIA_BEGIN) {
		ANESTHESIA_BEGIN = aNESTHESIA_BEGIN;
	}

	public String getANESTHESIA_END() {
		return ANESTHESIA_END;
	}

	public void setANESTHESIA_END(String aNESTHESIA_END) {
		ANESTHESIA_END = aNESTHESIA_END;
	}

	public String getASA_LEVEL_CD() {
		return ASA_LEVEL_CD;
	}

	public void setASA_LEVEL_CD(String aSA_LEVEL_CD) {
		ASA_LEVEL_CD = aSA_LEVEL_CD;
	}

	public String getSPILE_SORT() {
		return SPILE_SORT;
	}

	public void setSPILE_SORT(String sPILE_SORT) {
		SPILE_SORT = sPILE_SORT;
	}

	public String getANESTHESIA_POSTURE() {
		return ANESTHESIA_POSTURE;
	}

	public void setANESTHESIA_POSTURE(String aNESTHESIA_POSTURE) {
		ANESTHESIA_POSTURE = aNESTHESIA_POSTURE;
	}

	public String getBREATHE_TYPE_CD() {
		return BREATHE_TYPE_CD;
	}

	public void setBREATHE_TYPE_CD(String bREATHE_TYPE_CD) {
		BREATHE_TYPE_CD = bREATHE_TYPE_CD;
	}

	public String getANESTHESIA_DESCRIBE() {
		return ANESTHESIA_DESCRIBE;
	}

	public void setANESTHESIA_DESCRIBE(String aNESTHESIA_DESCRIBE) {
		ANESTHESIA_DESCRIBE = aNESTHESIA_DESCRIBE;
	}

	public String getANESTHESIA_COMPL_CD() {
		return ANESTHESIA_COMPL_CD;
	}

	public void setANESTHESIA_COMPL_CD(String aNESTHESIA_COMPL_CD) {
		ANESTHESIA_COMPL_CD = aNESTHESIA_COMPL_CD;
	}

	public String getPUNCTURE_SORT_CD() {
		return PUNCTURE_SORT_CD;
	}

	public void setPUNCTURE_SORT_CD(String pUNCTURE_SORT_CD) {
		PUNCTURE_SORT_CD = pUNCTURE_SORT_CD;
	}

	public String getPUNCTURE_PROC() {
		return PUNCTURE_PROC;
	}

	public void setPUNCTURE_PROC(String pUNCTURE_PROC) {
		PUNCTURE_PROC = pUNCTURE_PROC;
	}

	public String getANESTHESIA_EFFECT() {
		return ANESTHESIA_EFFECT;
	}

	public void setANESTHESIA_EFFECT(String aNESTHESIA_EFFECT) {
		ANESTHESIA_EFFECT = aNESTHESIA_EFFECT;
	}

	public String getPREANAESTHETIC_MEDICINE() {
		return PREANAESTHETIC_MEDICINE;
	}

	public void setPREANAESTHETIC_MEDICINE(String pREANAESTHETIC_MEDICINE) {
		PREANAESTHETIC_MEDICINE = pREANAESTHETIC_MEDICINE;
	}

	public String getWEIGHT() {
		return WEIGHT;
	}

	public void setWEIGHT(String wEIGHT) {
		WEIGHT = wEIGHT;
	}

	public String getTEMPERATURE() {
		return TEMPERATURE;
	}

	public void setTEMPERATURE(String tEMPERATURE) {
		TEMPERATURE = tEMPERATURE;
	}

	public String getPULSE() {
		return PULSE;
	}

	public void setPULSE(String pULSE) {
		PULSE = pULSE;
	}

	public String getBREATHE_RATE() {
		return BREATHE_RATE;
	}

	public void setBREATHE_RATE(String bREATHE_RATE) {
		BREATHE_RATE = bREATHE_RATE;
	}

	public String getSYSTOLIC_PRESSURE() {
		return SYSTOLIC_PRESSURE;
	}

	public void setSYSTOLIC_PRESSURE(String sYSTOLIC_PRESSURE) {
		SYSTOLIC_PRESSURE = sYSTOLIC_PRESSURE;
	}

	public String getDIASTOLIC_PRESSURE() {
		return DIASTOLIC_PRESSURE;
	}

	public void setDIASTOLIC_PRESSURE(String dIASTOLIC_PRESSURE) {
		DIASTOLIC_PRESSURE = dIASTOLIC_PRESSURE;
	}
	
	

	public String getENTER_DATE_TIME() {
		return ENTER_DATE_TIME;
	}

	public void setENTER_DATE_TIME(String eNTER_DATE_TIME) {
		ENTER_DATE_TIME = eNTER_DATE_TIME;
	}

	public String getIN_DATE_TIME() {
		return IN_DATE_TIME;
	}

	public void setIN_DATE_TIME(String iN_DATE_TIME) {
		IN_DATE_TIME = iN_DATE_TIME;
	}

	public String getOUT_DATE_TIME() {
		return OUT_DATE_TIME;
	}

	public void setOUT_DATE_TIME(String oUT_DATE_TIME) {
		OUT_DATE_TIME = oUT_DATE_TIME;
	}

	@Override
	public String toString() {
		return "BeanTarget [ANESTHESIA_ID=" + ANESTHESIA_ID + ", OPERATION_ID=" + OPERATION_ID + ", CASE_OBJECT_ID="
				+ CASE_OBJECT_ID + ", ANESTHESIA_METHODS=" + ANESTHESIA_METHODS + ", ANAESTHETIST_ID=" + ANAESTHETIST_ID
				+ ", ANESTHESIA_BEGIN=" + ANESTHESIA_BEGIN + ", ANESTHESIA_END=" + ANESTHESIA_END + ", ASA_LEVEL_CD="
				+ ASA_LEVEL_CD + ", SPILE_SORT=" + SPILE_SORT + ", ANESTHESIA_POSTURE=" + ANESTHESIA_POSTURE
				+ ", BREATHE_TYPE_CD=" + BREATHE_TYPE_CD + ", ANESTHESIA_DESCRIBE=" + ANESTHESIA_DESCRIBE
				+ ", ANESTHESIA_COMPL_CD=" + ANESTHESIA_COMPL_CD + ", PUNCTURE_SORT_CD=" + PUNCTURE_SORT_CD
				+ ", PUNCTURE_PROC=" + PUNCTURE_PROC + ", ANESTHESIA_EFFECT=" + ANESTHESIA_EFFECT
				+ ", PREANAESTHETIC_MEDICINE=" + PREANAESTHETIC_MEDICINE + ", WEIGHT=" + WEIGHT + ", TEMPERATURE="
				+ TEMPERATURE + ", PULSE=" + PULSE + ", BREATHE_RATE=" + BREATHE_RATE + ", SYSTOLIC_PRESSURE="
				+ SYSTOLIC_PRESSURE + ", DIASTOLIC_PRESSURE=" + DIASTOLIC_PRESSURE + ", ENTER_DATE_TIME="
				+ ENTER_DATE_TIME + ", IN_DATE_TIME=" + IN_DATE_TIME + ", OUT_DATE_TIME=" + OUT_DATE_TIME
				+ ", SCHEDULED_DATE_TIME=" + SCHEDULED_DATE_TIME + "]";
	}

	
	

	
}
